import Head from 'next/head'
import { Icon } from 'src/components/Icon'
import * as S from '../styles/pages/Home'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <S.Hero>Open  Start</S.Hero>
        <Icon aria-label='seta para direita na cor purple' src='arrow' width='30px'/>
      </main>
    </>
  )
}
