import Head from 'next/head'
import * as S from '../styles/pages/Home'
import { Button } from 'src/components/Button/style'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <S.Hero>Open  Start</S.Hero>
        <Button>Pudim</Button>
      </main>
    </>
  )
}
